import { PricingPlan } from "../types";

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: "free",
    name: "Free",
    monthlyPrice: 0,
    yearlyPrice: 0,
    description: "Get started with basic ATS analysis",
    features: [
      "3 resume scans total",
      "ATS match score",
      "Basic keyword analysis",
      "Formatting check",
    ],
    cta: "Get Started Free",
    stripePriceIdMonthly: "",
    stripePriceIdYearly: "",
  },
  {
    id: "pro",
    name: "Pro",
    monthlyPrice: 6.99,
    yearlyPrice: 4.99,
    description: "Everything you need to land your next job",
    features: [
      "Unlimited resume scans",
      "Full AI-powered analysis",
      "Score improvement tracking",
      "Resume history",
      "Detailed suggestions",
      "Keyword gap analysis",
      "Skills breakdown",
      "Priority support",
    ],
    cta: "Start Pro",
    popular: true,
    stripePriceIdMonthly: process.env.NEXT_PUBLIC_STRIPE_PRO_MONTHLY_PRICE_ID || "",
    stripePriceIdYearly: process.env.NEXT_PUBLIC_STRIPE_PRO_YEARLY_PRICE_ID || "",
  },
  {
    id: "teams",
    name: "Teams",
    monthlyPrice: 15.99,
    yearlyPrice: 13.99,
    description: "For teams and organizations",
    features: [
      "Everything in Pro",
      "Multiple team members",
      "Shared dashboard",
      "Shared scan history",
      "Team analytics",
      "Admin controls",
      "Dedicated support",
    ],
    cta: "Start Teams",
    stripePriceIdMonthly: process.env.NEXT_PUBLIC_STRIPE_TEAMS_MONTHLY_PRICE_ID || "",
    stripePriceIdYearly: process.env.NEXT_PUBLIC_STRIPE_TEAMS_YEARLY_PRICE_ID || "",
  },
];
